---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.14

platforms:
  - name: ubuntu-14.04
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[opera_test::default]
      - recipe[opera_test::x11]
    attributes:
  - name: beta
    run_list:
      - recipe[opera_test::default]
      - recipe[opera_test::x11]
    attributes:
      opera:
        browser:
          version: beta
