---
driver:
  name: vagrant
  ssh:
    insert_key: false

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.14

platforms:
  - name: ubuntu1404-desktop
    driver:
      box: boxcutter/ubuntu1404-desktop
      gui: true
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
  - name: macosx-10.10.4

suites:
  - name: default
    run_list:
      - recipe[opera_test::default]
      - recipe[opera_test::version]
    attributes:
  - name: beta
    run_list:
      - recipe[opera_test::default]
      - recipe[opera_test::version]
    attributes:
      opera:
        track: beta
