# Usage: KITCHEN_YAML=.kitchen.macosx.yml kitchen list
---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
      memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.14

platforms:
  - name: macosx-10.10
    driver:
      box: macosx-10.10

suites:
  - name: default
    run_list:
      - recipe[opera_test::default]
      - recipe[opera_test::version]
    attributes:
  - name: beta
    run_list:
      - recipe[opera_test::default]
      - recipe[opera_test::version]
    attributes:
      opera:
        track: beta
